{{- if has "cert-manager" .Values.enabledApps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-25"
spec:
  project: default
  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: v1.*.*
      helm:
        releaseName: cert-manager
        valueFiles:
          - $repo/kubernetes/helm/cert-manager/values.yaml
          - $repo/kubernetes/helm/cert-manager/values-{{ .Values.env }}.yaml
    - path: kubernetes/kustomizations/cert-manager/overlays/{{ .Values.env }}
      repoURL: "{{ .Values.spec.sources.repoURL }}"
      targetRevision: "{{ .Values.spec.sources.targetRevision }}"
      ref: repo
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
      refresh: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: restricted
        pod-security.kubernetes.io/warn: restricted
{{- end }}
