{{- if has "cilium" .Values.enabledApps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-80"
spec:
  project: default
  sources:
    - path: .
      repoURL: oci://quay.io/cilium/charts/cilium
      targetRevision: 1.*
      helm:
        releaseName: cilium
        valueFiles:
          - $repo/kubernetes/helm/cilium/values.yaml
          - $repo/kubernetes/helm/cilium/values-{{ .Values.env }}.yaml
    - path: kubernetes/kustomizations/cilium/overlays/{{ .Values.env }}
      repoURL: "{{ .Values.spec.sources.repoURL }}"
      targetRevision: "{{ .Values.spec.sources.targetRevision }}"
      ref: repo
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
      refresh: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: restricted
        pod-security.kubernetes.io/warn: restricted
{{- end }}
