global:
  image:
    repository: ghcr.io/theadzik/custom-argocd
    tag: ""

  networkPolicy:
    create: true
    defaultDenyIngress: true

  priorityClassName: "system-cluster-critical"

configs:
  params:
    server.insecure: false

server:
  service:
    annotations:
      traefik.ingress.kubernetes.io/service.serversscheme: https
      traefik.ingress.kubernetes.io/service.serverstransport: argocd-argocd-server-transport@kubernetescrd
  ingress:
    enabled: true
    ingressClassName: "traefik"
    tls: true

repoServer:
  env:
    - name: GITCRYPT_KEY_PATH
      value: "/git-crypt/git-crypt-key"
  volumeMounts:
    - mountPath: /git-crypt
      name: git-crypt
      readOnly: true
  volumes:
    - name: git-crypt
      secret:
        secretName: git-crypt-secret
