{
 "title": "Main",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(node_hwmon_temp_celsius)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Failed Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{phase=\"Failed\"}==1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}