import glob
import os
import re

APPLICATION_FILE_EXTENSION = "*.yaml"

search_path = os.getenv("APPLICATIONS_PATH", "../../manifests/applications/")
output_file_path = os.getenv("SYNC_FILE_NAME", "sync-waves.md")

# Get priorities
applications = {}

for filename in glob.glob(os.path.join(search_path, APPLICATION_FILE_EXTENSION)):
    if re.search("kustomization", filename):
        continue
    application_name = os.path.basename(filename).split(".")[0]
    application_file = open(filename, "r")
    sync_priority = 0
    for line in application_file:
        if re.search("argocd.argoproj.io/sync-wave", line):
            sync_priority = int(re.search("(-|)[0-9]+", line).group(0))
            break

    if applications.get(sync_priority, None):
        applications[sync_priority].append(application_name)
    else:
        applications[sync_priority] = [application_name]

    application_file.close()

# Generate markdown file
inventory = open(search_path + output_file_path, "w")

inventory.write("# Application Sync Wave inventory\n\n")
inventory.write("This file is automatically generated. Do not edit manually.\n\n")


inventory.write("## Sync Waves\n\n")
for key in sorted(applications.keys()):
    inventory.write(f"* Priority: {key}\n")
    for entry in applications[key]:
        inventory.write(f"    * {entry}\n")

inventory.close()
