admissionController:
  registerWebhook: false
  certGen:
    enabled: false
  certManager:
    enabled: true
    createSelfSignedIssuer:
      enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 64Mi

recommender:
  replicas: 1
  podDisruptionBudget:
    enabled: false
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
  extraArgs:
    - --round-memory-bytes=1048576 # 1 MiB

updater:
  replicas: 1
  podDisruptionBudget:
    enabled: false
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
  extraArgs:
    - --in-place-skip-disruption-budget=true
