{{- if .Values.resourceClaimTemplate.enabled }}
apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: {{ .Values.resourceClaimTemplate.name }}
  namespace: {{ .Release.Namespace }}
spec:
  spec:
{{ toYaml .Values.resourceClaimTemplate.spec | indent 4 }}
{{- end }}
