{{- if .Values.vpa.enabled }}
{{- range $svcName, $svc := .Values.services }}
{{- if $svc.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ $svcName }}
  namespace: {{ $.Release.Namespace }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ $svcName }}
  updatePolicy:
    minReplicas: 1
    updateMode: {{ dig "vpa" "updateMode" $.Values.vpa.updateMode $svc }}
  resourcePolicy:
    containerPolicies:
    - containerName: "*"
      minAllowed:
        cpu: 100m
        memory: 128Mi
      controlledResources:
        - cpu
        - memory
      controlledValues: RequestsOnly
---
{{- end }}
{{- end }}
{{- end }}
