- name: Create git-crypt version file.
  ansible.builtin.copy:
    content: ""
    dest: "{{ downloads_dir }}/git-crypt-{{ gitcrypt_version }}"
    force: false
  register: gitcrypt_version

- name: Download git-crypt.
  when: gitcrypt_version.changed
  ansible.builtin.get_url:
    url: "{{ gitcrypt_download_url }}"
    dest: "{{ downloads_dir }}/git-crypt"
    mode: "755"
  become: true

- name: Check SHA256 sum
  when: "gitcrypt_version.changed"
  ansible.builtin.stat:
    checksum_algorithm: sha256
    path: "{{ downloads_dir }}/git-crypt"
  register: gitcrypt_file

  # This fails if a new version is released or someone tempers with the file
- name: Downloaded git-crypt matches saved sha256
  when: "gitcrypt_version.changed"
  ansible.builtin.assert:
    that: "gitcrypt_sha256 == gitcrypt_file.stat.checksum"  # pragma: allowlist secret

- name: Move git-crypt to install location
  when: "gitcrypt_version.changed"
  ansible.builtin.copy:
    remote_src: true
    src: "{{ downloads_dir }}/git-crypt"
    dest: "/usr/bin/git-crypt"
  become: true

- name: Install pre-commit and hook dependencies using pipx.
  community.general.pipx:
    name: "{{ item }}"
    state: latest
    executable: "{{ pipx_executable }}"
  loop:
    - pre-commit
    - detect-secrets

- name: Install hook dependencies using brew.
  community.general.homebrew:
    name: hadolint
    state: latest
