apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blog-dev
resources:
  - ../../base
patches:
  - path: ingress-metadata.yaml
    target:
      kind: Ingress
      name: zmuda-pro-blog
  - path: ingress-host-patch.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: zmuda-pro-blog
  - path: deployment-replicas-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: zmuda-pro-blog
commonLabels:
  app.kubernetes.io/instance: dev
