vscode_keyring_path: /etc/apt/keyrings/microsoft.gpg
vscode_gpg_url: https://packages.microsoft.com/keys/microsoft.asc
vscode_repo_file: vscode

arch_mapping:
  x86_64: amd64
  aarch64: arm64
  armv7l: armhf
