deployment:
  replicas: 2
  minReadySeconds: 10

podDisruptionBudget:
  enabled: true
  minAvailable: 1

priorityClassName: "system-cluster-critical"

topologySpreadConstraints:
  - labelSelector:
      matchLabels:
        app.kubernetes.io/name: "{{ template \"traefik.name\" . }}"
    matchLabelKeys:
      - pod-template-hash
    maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: DoNotSchedule

logs:
  access:
    enabled: true
    format: json
  fields:
    headers:
      names:
        User-Agent: keep

ports:
  web:
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

service:
  type: LoadBalancer
  loadBalancerClass: io.cilium/l2-announcer
