apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  labels:
    app: vaultwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
      ingress: exposed
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vaultwarden
        ingress: exposed
    spec:
      priorityClassName: high-priority
      imagePullSecrets:
        - name: dockerhub-image-pull-secret
      initContainers:
        - name: restore
          image: theadzik/vw-restore:2026.2.1
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /home/vaultwarden
              name: rclone-conf
            - mountPath: /data
              name: data
            - mountPath: /backup
              name: backup
            - mountPath: /tmp
              name: tmp
          envFrom:
            - secretRef:
                name: backup-encryption-secret
          env:
            - name: RCLONE_TEMP_DIR
              value: "/tmp"
            - name: RCLONE_CONFIG_DIR
              value: "/tmp"
            - name: XDG_CONFIG_HOME
              value: "/tmp"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
      containers:
        - name: vaultwarden
          image: vaultwarden/server:1.35.7-alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: "TCP"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
          envFrom:
            - secretRef:
                name: vw-secrets
          env:
            - name: DOMAIN
              value: "https://vault.zmuda.pro"
            - name: SIGNUPS_ALLOWED
              value: "false"
            - name: SIGNUPS_VERIFY
              value: "true"
            - name: PUSH_ENABLED
              value: "true"
            - name: ICON_CACHE_TTL
              value: "0"
            - name: DISABLE_ICON_DOWNLOAD
              value: "true"
          volumeMounts:
            - mountPath: /data
              name: data
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: vaultwarden-data
        - name: backup
          persistentVolumeClaim:
            claimName: vaultwarden-backup
        - name: rclone-conf
          secret:
            secretName: rclone-secret
        - name: tmp
          emptyDir: {}
