tty: true
falcosidekick:
  enabled: true
  webui:
    enabled: true
    replicaCount: 1
    customLabels:
      dns-type: internal
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: lets-encrypt-prod
      hosts:
        - host: falcosidekick.zmuda.pro
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: falcosidekick-tls
          hosts:
            - falcosidekick.zmuda.pro
    existingSecret: falcosidekick-ui-config
  config:
    existingSecret: falcosidekick-config
    smtp:
      minimumpriority: "error"

customRules:
  rules-cilium-exceptions.yaml: |-
    - rule: Drop and execute new binary in container
      exceptions:
        - name: cilium_cni_exec
          fields: [proc.exepath, proc.name]
          comps: [=, =]
          values:
            - [/opt/cni/bin/cilium-cni, cilium-cni]
            - [/opt/cni/bin/cilium-sysctlfix, cilium-sysctlfix]
      override:
        exceptions: append

    - rule: Packet socket created in container
      exceptions:
        - name: cilium_agent_packet_socket
          fields: [k8s.ns.name, container.image.repository, proc.name]
          comps: [=, =, =]
          values:
            - [kube-system, quay.io/cilium/cilium, cilium-agent]
      override:
        exceptions: append
