apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zmuda-pro-blog
resources:
  - deployment.yaml
  - gateway.yaml
  - ingress.yaml
  - namespace.yaml
  - nwp.yaml
  - service.yaml
  - ../image-pull-secret
