image:
  pullPolicy: IfNotPresent

registries:
  - name: Docker Hub
    prefix: docker.io
    api_url: https://registry-1.docker.io
    credentials: pullsecret:argocd/dockerhub-image-pull-secret
    limit: 10
    default: true
