apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blog
resources:
  - ../../base
patches:
  - path: ingress-metadata.yaml
  - path: ingress-host-patch.yaml
  - path: deployment-replicas-patch.yaml
    target:
      group: networking.k8s.io
      kind: Ingress
      name: zmuda-pro-blog
      version: v1
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: prod
