import os
import re

import yaml

search_path = os.getenv("APPLICATIONS_PATH", "./")
output_file_path = os.getenv("OUTPUT_PATH", "./sync-waves-inventory.md")

# Get priorities
applications = {}

# Templates files excluding starting with _ (helpers)
application_file_paths = [
    os.path.join(search_path, f)
    for f in os.listdir(search_path)
    if f.endswith(".yaml") and not f.startswith("_")
]
for file_path in application_file_paths:
    application_file = open(file_path, "r")
    content = application_file.read()
    # Sanitize Go templating to avoid YAML parsing errors
    content_sanitized = re.sub(
        r'(?<!["\'])\{\{.*?\}\}(?!["\'])',
        lambda m: f'"{m.group(0)}"',
        content,
        flags=re.S,  # match multiline
    )
    documents = yaml.safe_load_all(content_sanitized)
    for document in documents:
        if document.get("kind", "") != "Application":
            continue

        application_name = document.get("metadata", {}).get("name", "unknown")
        application_priority = int(
            document.get("metadata", {})
            .get("annotations", {})
            .get("argocd.argoproj.io/sync-wave", "0")
        )

        if applications.get(application_priority, None):
            applications[application_priority].append(application_name)
        else:
            applications[application_priority] = [application_name]

    application_file.close()

# Generate Markdown file
inventory = open(output_file_path, "w", newline="\n")

inventory.write("# Application Sync Wave inventory\n\n")
inventory.write("This file is automatically generated. Do not edit manually.\n\n")

inventory.write("## Sync Waves\n\n")
for key in sorted(applications.keys()):
    inventory.write(f"* Priority: {key}\n")
    for entry in sorted(applications[key]):
        inventory.write(f"  * {entry}\n")

inventory.close()
