import os
import re

import yaml

APPLICATION_FILE_EXTENSION = "*.yaml"
KUSTOMIZATION_FILE_NAME = "kustomization.yaml"

search_path = os.getenv("APPLICATIONS_PATH", "../../../manifests/applications/")
print(search_path)
output_file_name = os.getenv("SYNC_FILE_NAME", "sync-waves.md")

# Get priorities
applications = {}

with open(search_path+KUSTOMIZATION_FILE_NAME) as file:
    kustomization = yaml.load(file, Loader=yaml.FullLoader)

for filename in kustomization["resources"]:
    print(filename)
    application_name = filename.split(".")[0]
    print(search_path+filename)
    application_file = open(search_path+filename, "r")
    sync_priority = 0
    for line in application_file:
        if re.search("argocd.argoproj.io/sync-wave", line):
            sync_priority = int(re.search("(-|)[0-9]+", line).group(0))
            break

    if applications.get(sync_priority, None):
        applications[sync_priority].append(application_name)
    else:
        applications[sync_priority] = [application_name]

    application_file.close()

# Generate markdown file
inventory = open(search_path + output_file_name, "w", newline="\n")

inventory.write("# Application Sync Wave inventory\n\n")
inventory.write("This file is automatically generated. Do not edit manually.\n\n")


inventory.write("## Sync Waves\n\n")
for key in sorted(applications.keys()):
    inventory.write(f"* Priority: {key}\n")
    for entry in sorted(applications[key]):
        inventory.write(f"    * {entry}\n")

inventory.close()
