import os
import re

import yaml

search_path = os.getenv("APPLICATIONS_PATH", "./")
output_file_path = os.getenv("OUTPUT_PATH", "./sync-waves-inventory.md")

# Get priorities
entries = {}  # Format: {priority: [(name, kind), ...]}

# Templates files excluding starting with _ (helpers)
application_file_paths = [
    os.path.join(search_path, f)
    for f in os.listdir(search_path)
    if f.endswith(".yaml") and not f.startswith("_")
]
for file_path in application_file_paths:
    application_file = open(file_path, "r")
    content = application_file.read()
    # Sanitize Go templating to avoid YAML parsing errors
    content_sanitized = re.sub(
        r'(?<!["\'\`])\{\{(?:[^{}]|(?:\{\{)|(?:\}\}))*\}\}(?!["\'\`])',
        lambda m: f'"{m.group(0)}"',
        content,
        flags=re.S,  # match multiline
    )
    documents = yaml.safe_load_all(content_sanitized)
    for document in documents:
        kind = document.get("kind", "")
        if kind not in ("Application", "ApplicationSet"):
            continue

        entry_name = document.get("metadata", {}).get("name", "unknown")

        # Sync-wave location differs by kind
        if kind == "ApplicationSet":
            entry_priority = int(
                document.get("spec", {})
                .get("template", {})
                .get("metadata", {})
                .get("annotations", {})
                .get("argocd.argoproj.io/sync-wave", "0")
            )
        else:  # Application
            entry_priority = int(
                document.get("metadata", {})
                .get("annotations", {})
                .get("argocd.argoproj.io/sync-wave", "0")
            )

        if entries.get(entry_priority, None):
            entries[entry_priority].append((entry_name, kind))
        else:
            entries[entry_priority] = [(entry_name, kind)]

    application_file.close()

# Generate Markdown file
inventory = open(output_file_path, "w", newline="\n")

inventory.write("# Application Sync Wave inventory\n\n")
inventory.write("This file is automatically generated. Do not edit manually.\n\n")

inventory.write("## Sync Waves\n\n")
for key in sorted(entries.keys()):
    inventory.write(f"* Priority: {key}\n")
    for entry_name, entry_kind in sorted(entries[key], key=lambda x: x[0]):
        inventory.write(f"  * {entry_name} ({entry_kind})\n")

inventory.close()
