apiVersion: apps/v1
kind: Deployment
metadata:
  name: zmuda-pro-blog
  labels:
    app: zmuda-pro-blog
spec:
  template:
    spec:
      priorityClassName: high-priority
      imagePullSecrets:
        - name: dockerhub-image-pull-secret
      containers:
        - name: nginx
          image: theadzik/zmuda-pro-blog:2026.5.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: "TCP"
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /var/cache/nginx
              name: cache
            - mountPath: /var/run
              name: run
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 10003
        runAsGroup: 20003
        fsGroup: 20003
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: cache
          emptyDir: {}
        - name: run
          emptyDir: {}
