name: custom-argocd-build
on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/custom-argocd.yaml"
      - "kubernetes/bootstrap/charts/app-of-apps/templates/argocd.yaml"
      - "apps/custom-argocd/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/custom-argocd.yaml"
      - "kubernetes/bootstrap/charts/app-of-apps/templates/argocd.yaml"
      - "apps/custom-argocd/**"
jobs:
  get-version:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    outputs:
      app_version: ${{ steps.get_version.outputs.app_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Get App Version
        id: get_version
        run: |
          set -e

          chart_name=$(yq -er '.spec.sources[] | select(has("chart")) | .chart' "$ARGOCD_TEMPLATE_FILE")
          repo_url=$(yq -er '.spec.sources[] | select(has("chart")) | .repoURL' "$ARGOCD_TEMPLATE_FILE")
          chart_version=$(yq -er '.spec.sources[] | select(has("chart")) | .targetRevision' "$ARGOCD_TEMPLATE_FILE")

          echo "Repository url: $repo_url"
          echo "Chart name: $chart_name"
          echo "Chart version: $chart_version"

          helm repo add argocd $repo_url
          app_version=$(helm search repo argocd/$chart_name --version $chart_version -o json | jq -r '.[0].app_version')
          echo "App version: $app_version"

          echo "app_version=$app_version" >> $GITHUB_OUTPUT
        env:
          ARGOCD_TEMPLATE_FILE: "${{ github.workspace }}/kubernetes/bootstrap/charts/app-of-apps/templates/argocd.yaml"

  build:
    needs: get-version
    permissions:
      contents: read
      id-token: write
      attestations: write
      artifact-metadata: write
    uses: ./.github/workflows/build-and-push.yaml
    with:
      git-ref: ${{ github.event.pull_request.head.ref || github.ref_name }}
      docker-tag: ${{ needs.get-version.outputs.app_version }}
      build-args: |
        TAG=${{ needs.get-version.outputs.app_version }}
      image-name: "custom-argocd"
      context-path: "apps/custom-argocd"
