name: vw-restore-build

on:
  push:
    tags:
      - "vw-restore-*"
  schedule:
    - cron: "22 12 * * 6"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  get-tag:
    uses: ./.github/workflows/get-tag.yaml
    with:
      tag-prefix: "vw-restore-"
  restore-build-push:
    uses: ./.github/workflows/build-and-push.yaml
    needs: get-tag
    permissions:
      contents: read
      id-token: write
      attestations: write
      artifact-metadata: write
    with:
      git-ref: ${{ needs.get-tag.outputs.git_tag }}
      docker-tag: ${{ needs.get-tag.outputs.docker_tag }}
      image-name: "vw-restore"
      context-path: "apps/vaultwarden/restore"
    secrets: inherit
